### ISSUE TITLE
core libvlc error: No plugins found! 

### ISSUE THREAD

**Issue by probonopd** [abhay44/media_player#1]
On Xubuntu 16.04,

```
me@host:~$ /home/me/Downloads/media_player.AppImage
[0000000000a18a28] core libvlc error: No plugins found! Check your VLC installation.
VLC-Qt Error: libvlc failed to load!
Segmentation fault
```

Note that AppImages must not have any dependencies other than what can be reasonably expected to be part of each target system. Hence, please bundle libvlc and its plugins inside the AppImage so that it becomes standalone.

**Comment by abhay44** [comment]
I too got this error!Just try exporting vlc plugin path of your system.I already mentioned it in the README.md file.

**Comment by probonopd** [comment]
There is no "vlc plugin path of your system" since my system has no VLC. AppImages must not have any dependencies other than what can be reasonably expected to be part of each target system. Hence, please bundle libvlc and its plugins inside the AppImage so that it becomes standalone.

**Comment by abhay44** [comment]
help wanted in binding vlc libraries with the appimage

**Comment by abhay44** [comment]
As suggested by the vlc-qt developer, it's good to use the system vlc libraries rather than using custom vlc libraries.
